source 'https://github.com/CocoaPods/Specs.git'

target 'MSTDropDownPresentationController', :exclusive => true do
  pod "MSTDropDownPresentationController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MSTDropDownPresentationController", :path => "../"

  
end
